YEAR = 2024
VNUM = 14		; >13

;;@PROTASI = 1
@DILONO_ELEGXO = 1

@EPSONLQ590 = 100
@EPSONLQ870 = 101

@WINDOWS 	= WINSEGM

AUSTRIA	= "A"
CROATIA 	= "B"
GERMANY 	= "C"
GERMANY1	= "D"
FRANCE	= "E"
HUNGAR	= "F"
SERBIA	= "G"
BULGARIA	= "H"
SPAIN	= "I"
SWEDEN	= "J"
SWISS	= "K"
ITALY	= "L"
PRINT6ADES 	= "M"
STILESA4	= "N"
RUMANIA	= "O"
PRINT4ADES	= "P"
PRINT8ADES	= "Q"
PRINT10ADES	= "R"
TURKEY	= "S"
PORTUGAL	= "T"
GREECE	= "U"

cr	= 13
lf	= 10
LEFT_ARROW	= 75
RIGHT_ARROW	= 77
UP_ARROW	= 72
DOWN_ARROW	= 80
CTRL_LEFT	= 115
CTRL_RIGHT	= 116
_HOME	= 47h
_END	= 4fh
_INS	= 82

BUFDATA	= 65500	; XOROS DATA [ POY DIMIOYRGEITE APO TA ASCII ]
BUFASCII	= 63840	; XOROS ASCII [ 48 Byte x 14 OroiSthnOthoni * 95 Othones ]

INCLUDE	mylib.inc
INCLUDE	sdir.inc
INCLUDE	sindisk.inc
INCLUDE	snaioxi.inc
INCLUDE	keys.inc
INCLUDE	globals.inc
